---
webs:
  worten:
    ...
  game:
    ...
  mediamarkt:
    - url: 'https://www.mediamarkt.es/es/product/<<prod>>.html'
      name: 'My super product'
    - url: 'https://www.mediamarkt.es/es/product/<<prod>>.html'
      name: 'My super product 2'
  eci:
    - url: 'https://www.elcorteingles.es/....'
      name: 'My super product'
    - url: 'https://www.elcorteingles.es/....'
      name: 'My super product 2'
  amazon:
    - url: 'https://www.amazon.es/dp/<<product-id>>'
      name: 'My super product'
    - url: 'https://www.amazon.es/<<amazon-prod-name>>/dp/<<product-id>>'
      name: 'My super product 2'
telegram:
  token: '0000000000:supertelegramtoken'
  chatID: 'chatid'
  message: 'Product stock' # General message for telegram chat